//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///out vec4 FragColor;
        ///
        ///in vec3 LineColor;
        ///
        ///void main()
        ///{
        ///    FragColor = vec4(LineColor, 1.0);
        ///}.
        /// </summary>
        public static string axis_frag_shader {
            get {
                return ResourceManager.GetString("axis_frag_shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///layout(location = 0) in vec3 in_position;
        ///
        ///out vec3 LineColor;
        ///
        ///uniform vec3 lineColor;
        ///uniform mat4 model;
        ///uniform mat4 view;
        ///uniform mat4 projection;
        ///
        ///void main()
        ///{
        ///    gl_Position = projection * view * model * vec4(in_position, 1.0);
        ///    LineColor = lineColor;
        ///}.
        /// </summary>
        public static string axis_vert_shader {
            get {
                return ResourceManager.GetString("axis_vert_shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box_crate {
            get {
                object obj = ResourceManager.GetObject("box_crate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///out vec4 FragColor;
        ///
        ///in vec3 FragPos;
        ///in vec3 Normal;
        ///in vec2 TexCoord;
        ///in float AmbientStrength;
        ///
        ///uniform vec3 objectColor;
        ///uniform vec3 ambientLightColor;
        ///uniform vec3 lightColor;
        ///uniform vec3 lightPos;
        ///uniform sampler2D ourTexture;
        ///
        ///void main()
        ///{
        ///    vec3 ambient = AmbientStrength * ambientLightColor;
        ///    vec3 norm = normalize(Normal);
        ///    vec3 lightDir = normalize(lightPos - FragPos);
        ///    float diff = max(dot(norm, lightDir), 0.0);
        ///    vec3 diffuse = diff * lightCol [rest of string was truncated]&quot;;.
        /// </summary>
        public static string default_frag_shader {
            get {
                return ResourceManager.GetString("default_frag_shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///layout(location = 0) in vec3 in_position;
        ///layout(location = 1) in vec2 in_texCoord;
        ///layout(location = 2) in vec3 in_normals;
        ///
        ///out vec3 FragPos;
        ///out vec3 Normal;
        ///out vec2 TexCoord;
        ///out float AmbientStrength;
        ///
        ///uniform mat4 model;
        ///uniform mat4 view;
        ///uniform mat4 projection;
        ///uniform float ambientLightStrength;
        ///
        ///void main()
        ///{
        ///    gl_Position = projection * view * model * vec4(in_position, 1.0);
        ///    FragPos = vec3(model * vec4(in_position, 1.0));
        ///    TexCoord = in_texCoord;
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string default_vert_shader {
            get {
                return ResourceManager.GetString("default_vert_shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap editor_icon_atlas {
            get {
                object obj = ResourceManager.GetObject("editor_icon_atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///out vec4 FragColor;
        ///
        ///in vec4 LineColor;
        ///
        ///void main()
        ///{
        ///    FragColor = LineColor;
        ///}.
        /// </summary>
        public static string grid_frag_shader {
            get {
                return ResourceManager.GetString("grid_frag_shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///layout(location = 0) in vec3 in_position;
        ///
        ///out vec4 LineColor;
        ///
        ///uniform vec3 lineColor;
        ///uniform vec3 cam_pos;
        ///uniform mat4 model;
        ///uniform mat4 view;
        ///uniform mat4 projection;
        ///
        ///void main()
        ///{
        ///    float dist = distance(in_position, cam_pos);
        ///    gl_Position = projection * model * view * vec4(in_position, 1.0);
        ///    LineColor = vec4(lineColor, 1.0f / max((dist - 6.0f), 1.0f));
        ///}.
        /// </summary>
        public static string grid_vert_shader {
            get {
                return ResourceManager.GetString("grid_vert_shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///uniform sampler2D in_fontTexture;
        ///in vec4 color;
        ///in vec2 texCoord;
        ///out vec4 outputColor;
        ///void main()
        ///{
        ///    outputColor = color * texture(in_fontTexture, texCoord);
        ///}.
        /// </summary>
        public static string imgui_frag_shader {
            get {
                return ResourceManager.GetString("imgui_frag_shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///uniform mat4 projection_matrix;
        ///layout(location = 0) in vec2 in_position;
        ///layout(location = 1) in vec2 in_texCoord;
        ///layout(location = 2) in vec4 in_color;
        ///out vec4 color;
        ///out vec2 texCoord;
        ///void main()
        ///{
        ///    gl_Position = projection_matrix * vec4(in_position, 0, 1);
        ///    color = in_color;
        ///    texCoord = in_texCoord;
        ///}.
        /// </summary>
        public static string imgui_vert_shader {
            get {
                return ResourceManager.GetString("imgui_vert_shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///out vec4 FragColor;
        ///
        ///in vec3 LineColor;
        ///
        ///void main()
        ///{
        ///    FragColor = vec4(LineColor, 1.0f);
        ///}.
        /// </summary>
        public static string line_shape_frag_shader {
            get {
                return ResourceManager.GetString("line_shape_frag_shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///layout(location = 0) in vec3 in_position;
        ///
        ///out vec3 LineColor;
        ///
        ///uniform vec3 lineColor;
        ///uniform mat4 model;
        ///uniform mat4 view;
        ///uniform mat4 projection;
        ///
        ///void main()
        ///{
        ///    gl_Position = projection * model * view * vec4(in_position, 1.0);
        ///    LineColor = lineColor;
        ///}.
        /// </summary>
        public static string line_shape_vert_shader {
            get {
                return ResourceManager.GetString("line_shape_vert_shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap skybox_back {
            get {
                object obj = ResourceManager.GetObject("skybox_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap skybox_bottom {
            get {
                object obj = ResourceManager.GetObject("skybox_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///out vec4 FragColor;
        ///
        ///in vec3 TexCoords;
        ///
        ///uniform samplerCube skybox;
        ///
        ///void main()
        ///{    
        ///    FragColor = texture(skybox, TexCoords);
        ///}.
        /// </summary>
        public static string skybox_frag_shader {
            get {
                return ResourceManager.GetString("skybox_frag_shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap skybox_front {
            get {
                object obj = ResourceManager.GetObject("skybox_front", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap skybox_left {
            get {
                object obj = ResourceManager.GetObject("skybox_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap skybox_right {
            get {
                object obj = ResourceManager.GetObject("skybox_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap skybox_top {
            get {
                object obj = ResourceManager.GetObject("skybox_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330 core
        ///layout (location = 0) in vec3 in_pos;
        ///
        ///out vec3 TexCoords;
        ///
        ///uniform mat4 projection;
        ///uniform mat4 view;
        ///
        ///void main()
        ///{
        ///    TexCoords = in_pos;
        ///    gl_Position = projection * view * vec4(in_pos, 1.0);
        ///}.
        /// </summary>
        public static string skybox_vert_shader {
            get {
                return ResourceManager.GetString("skybox_vert_shader", resourceCulture);
            }
        }
    }
}
